feat: Implemented Endpoint to add a new user to the Waitlist
hngprojects/hng_boilerplate_python_fastapi_web pull request #210
Opened 2024-07-22 09:43 UTC by Nifilat

​

## Description

The waitlist endpoint was designed to manage user registrations and store user details for the product until it gets launched. This feature allows users to reserve their spot in line for future updates or access to the boilerplate. Key aspects of the implementation include:

- Users can sign up by providing their email address and full name
- There is validation to check for duplicate emails or if the name field is null
- A confirmation email is sent to the email address provided upon successful sign-up
- To protect against abuse, the waitlist endpoint incorporates rate-limiting

​

## Related Issue (Link to issue ticket)
[WAITLIST API-BACKEND](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/21)

​

## Motivation and Context

This ensures that users on the waitlist can have first-hand information about new features and when the product finally launches.

​

## How Has This Been Tested?

I have tested locally using both Postman and unit tests that I wrote
​

## Screenshots (if appropriate - Postman, etc):
### Success Response
<img width="706" alt="Screenshot 2024-07-22 at 07 53 53" src="https://github.com/user-attachments/assets/cfd09abf-41e6-4cf9-9521-b3c55728b6d3">

### Error Response
<img width="712" alt="Screenshot 2024-07-22 at 07 54 04" src="https://github.com/user-attachments/assets/295186f6-c155-4601-b5a9-f95e99458503">

<img width="764" alt="Screenshot 2024-07-22 at 07 53 28" src="https://github.com/user-attachments/assets/d785f1ed-8f46-47ef-ac27-a5d212cd0ce4">

​

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation as needed.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-07-24 21:39 UTC, Goketech requested changes
pull from dev branch, follow the file structure and make changes

2024-07-24 21:39 UTC, Goketech commented on .env.sample
> +MAIL_SERVER='smtp.gmail.com'
revert all changes in this file

2024-07-24 21:39 UTC, Goketech commented on tests/v1/test_waitlist.py
> +
mock db for testing

2024-07-27 11:24 UTC, joboy-dev commented on api/v1/routes/waitlist.py
> +router = APIRouter()
Use prefix here ans set it to /waitlist

2024-07-27 11:25 UTC, joboy-dev commented on api/v1/services/email/waitlist_email.py
There is a function handling emails

2024-07-27 11:25 UTC, joboy-dev requested changes
Make changes

2024-07-27 13:03 UTC, Nifilat commented
This is an old PR and can be closed. Someone already worked on this feature using the newly appointed spreadsheet method.On 27 Jul 2024, at 12:25, Adegbehingbe, Oluwakorede Joseph ***@***.***> wrote:﻿
@joboy-dev requested changes on this pull request.

Make changes

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-27 14:15 UTC, closed without merging