feat: Create a GET endpoint to Retrieve Client Testimonials
hngprojects/hng_boilerplate_python_fastapi_web pull request #217
Opened 2024-07-22 11:00 UTC by chionz

## Description

Created an API GET endpoint `/api/testimonials` that allows users to retrieve client testimonials. The endpoint supports fetching all testimonials with pagination, includes testimonial metadata, requires user authentication, and has proper error handling and rate limiting.

## Related Issue (Link to issue ticket)
[FEAT] Create a GET endpoint to Retrieve Client Testimonials #104

## Motivation and Context

This change is required to provide users with a way to easily access and retrieve client testimonials from our database. The endpoint is designed to handle large numbers of testimonials efficiently with pagination and includes necessary metadata such as client name, designation, date, and rating. It also implements rate limiting to restrict the number of requests a user can make to the endpoint.

## How Has This Been Tested?

- Added exactly 6 test testimonials to the database using `“seed.py”` and sent a GET request to `/api/testimonials?page=1` to verify correct pagination.
- Added a large number of testimonials (1000) to the database and sent a GET request to `/api/testimonials?page=1` to test handling of maximum allowable testimonials.
- Sent GET requests with invalid `rating` and `date` parameters to ensure proper validation and error handling.
- Implemented unit tests to test fetching all testimonials, pagination functionality, and error handling for invalid requests.

## Screenshots (if appropriate - Postman, etc):

![Screenshot from 2024-07-21 19-18-52](https://github.com/user-attachments/assets/a44c4c81-0460-464b-8328-004703afe1b5)
![Screenshot from 2024-07-22 10-25-50](https://github.com/user-attachments/assets/29dad569-ac38-486c-a5c2-d68729db2f80)
![Screenshot from 2024-07-22 10-23-57](https://github.com/user-attachments/assets/ffb72fe1-2fd4-4221-a702-4b6cd970636f)
![Screenshot from 2024-07-22 10-24-43](https://github.com/user-attachments/assets/843d7b56-12c7-4021-9086-76f66e73151f)
![Screenshot from 2024-07-22 10-25-29](https://github.com/user-attachments/assets/f9e03e9b-4301-45df-9925-23b0af786397)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-24 16:50 UTC, Goketech requested changes
17 files changed for this pr.

Pull changes made to dev branch, work with new models created.

Don't tamper with the migrations

2024-07-27 11:17 UTC, joboy-dev commented on api/utils/auth.py
> +bearer_scheme = HTTPBearer()
Please, what is this??

2024-07-27 11:17 UTC, joboy-dev commented on api/utils/auth.py
> +def get_current_user(db: Session = Depends(get_db), credentials: HTTPAuthorizationCredentials = Security(bearer_scheme)):
What is this for??
We have this already

2024-07-27 11:19 UTC, joboy-dev commented on api/v1/models/testimonials.py
> +class Testimonial(BaseModel, Base):
Remove Base from here

2024-07-27 11:20 UTC, joboy-dev commented on api/v1/models/testimonials.py
No need for id, created_at, updated_at

2024-07-27 11:22 UTC, joboy-dev requested changes
Make changes

2024-07-27 14:54 UTC, chionz commented
@joboy-dev I will close this PR. The new PR is at https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/481
check it out please

2024-07-27 14:55 UTC, chionz commented
@joboy-dev I will close this PR. The new PR is at https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/481
check it out please

2024-07-27 14:55 UTC, closed without merging