feat: add get-comment-by-id endpoint and testing
hngprojects/hng_boilerplate_python_fastapi_web pull request #374
Opened 2024-07-24 19:46 UTC by Oseni03

## Description

This pull request adds a new endpoint to the FastAPI application that allows users to retrieve a comment by its `comment_id`. The endpoint performs a database query to fetch the comment details and returns a JSON response with the comment information if found, or a 404 error if the comment does not exist.

## Motivation and Context

This change is required to provide an API endpoint for retrieving individual comments based on their unique identifier. It solves the problem of needing to fetch specific comment details, which is essential for various client-side functionalities such as displaying comment details in user interfaces.

## How Has This Been Tested?

The changes have been tested using `pytest` with the following tests:
- `test_get_comment_not_found`: Ensures that the endpoint returns a 404 error when a non-existent `comment_id` is requested.

Testing environment:
- SQLite database used for both development and testing.
- FastAPI's `TestClient` for endpoint testing.

## Screenshots (if appropriate - Postman, etc):

N/A

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-24 20:50 UTC, joboy-dev commented on api/v1/schemas/comment.py
Anything id should be a string, not UUID

2024-07-24 20:50 UTC, joboy-dev requested changes
Make use of services. Check api/v1/services folder for how to do this because database queries should not be in the routes.

2024-07-25 15:19 UTC, Goketech approved these changes

2024-07-25 15:39 UTC, Goketech commented
@joboy-dev

2024-07-25 16:12 UTC, joboy-dev approved these changes

2024-07-26 12:44 UTC, joboy-dev approved these changes

2024-07-26 21:29 UTC, Goketech approved these changes

2024-07-27 11:14 UTC, joboy-dev requested changes
Resolve your merge conflict

2024-07-27 14:17 UTC, Goketech approved these changes

2024-08-06 19:15 UTC, closed without merging