feat: create endpoint for changing user password
hngprojects/hng_boilerplate_python_fastapi_web pull request #399
Opened 2024-07-24 21:44 UTC by trevorjob

## Description

This pull request introduces an endpoint for changing the password of authenticated users.

​The changes include:
- **Endpoint Addition**: Added PATCH ``` /api/v1/users/current-user/change-password  ``` for changing user passwords.
- **Authentication**: Ensured the endpoint is secured and only accessible to authenticated users.
- **Validation**: Implemented checks for validating old passwords and ensuring new passwords meet security criteria.
- **Error Handling**: Added appropriate error messages for invalid requests and authentication failures.
- **Testing**: Added unit and integration tests to ensure functionality and edge cases are covered.

## Related Issue (Link to issue ticket)
[ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/284)

## Motivation and Context

This feature is essential to allow users to securely change their passwords.

## How Has This Been Tested?

- **Unit Tests**: Added tests to validate the endpoint responsible for changing user passwords.
- **Integration Tests**: Included end-to-end tests to ensure proper functionality and security.
**Tests Include:**
     * Changing a password with valid old and new passwords.
     * Ensuring the old password is correctly validated.
     * Handling validation errors and authentication failures.
​

## Screenshots (if appropriate - Postman, etc):
- **SUCCESSFULLY CHANGED PASSWORD**
![successfully_changed](https://github.com/user-attachments/assets/48b5f10e-b4ca-408d-899f-3936b7091d9d)

- **WITHOUT AUTHENTICATION HEADER**
![without_auth_header](https://github.com/user-attachments/assets/1ca8d362-3cb5-43ec-bfee-0403367742d7)

- **MISSING BODY ARGUMENTS**
![missing_arguments](https://github.com/user-attachments/assets/9b4d6678-08d0-4d83-8c7c-cb168061c074)

- **WRONG OLD PASSWORD**
![with_wrong_password](https://github.com/user-attachments/assets/a98294ca-6be0-47c5-8eea-1d39a29d7228)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-24 22:15 UTC, zxenonx requested changes
Thanks @trevorjob 
I left some comments

2024-07-24 22:15 UTC, zxenonx commented on api/v1/routes/user.py
> +@user.patch("/current-user/change-password", status_code=200)
```suggestion
@user.patch("/me/password", status_code=200)
```
or 
```suggestion
@user.patch("/:id/password", status_code=200)
```

2024-07-24 22:15 UTC, zxenonx commented on api/v1/services/user.py
> +        db.commit()
remove the comments

2024-07-24 22:15 UTC, zxenonx commented on tests/v1/change_user_password_test.py
> +CHANGE_PWD_ENDPOINT = "/api/v1/users/current-user/change-password"
update the route accordingly

2024-07-24 22:41 UTC, trevorjob commented
@zxenonx done

2024-07-24 22:57 UTC, Goketech requested changes

2024-07-24 22:57 UTC, Goketech commented on api/v1/routes/user.py
> +# from api.utils.dependencies import get_current_user
you added this comment

2024-07-24 23:05 UTC, trevorjob commented
@Goketech i've removed it

2024-07-24 23:22 UTC, Goketech approved these changes

2024-07-24 23:36 UTC, Goketech submitted a review, later dismissed

2024-07-25 06:20 UTC, Goketech approved these changes

2024-07-25 12:20 UTC, Goketech approved these changes

2024-07-25 12:20 UTC, Goketech commented
@bolexs

2024-07-25 13:15 UTC, bolexs commented
resolve conflicts

2024-07-25 13:18 UTC, trevorjob commented
@bolexs done

2024-07-25 13:24 UTC, Goketech approved these changes

2024-07-25 13:30 UTC, joboy-dev approved these changes

2024-07-25 15:21 UTC, joboy-dev submitted a review, later dismissed

2024-07-25 15:21 UTC, joboy-dev commented
@bolexs

2024-07-25 20:03 UTC, zxenonx requested changes
Thanks @trevorjob 
I left some comments

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          return user
```suggestion
        return check_model_existence(db, User, id)
        
```

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          return encoded_jwt
```suggestion
        return  jwt.encode(data, settings.SECRET_KEY, settings.ALGORITHM)

```

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          return encoded_jwt
```suggestion
        return jwt.encode(data, settings.SECRET_KEY, settings.ALGORITHM)

```

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>              pass
```suggestion

```

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          return user
```suggestion
        return db.query(User).filter(User.id == token.id).first()
```

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          # )
to remove

2024-07-25 20:03 UTC, zxenonx commented on api/v1/services/user.py
>          # Commit changes to deactivate the user
to remove

2024-07-25 20:03 UTC, zxenonx commented on tests/v1/change_user_password_test.py
> +
to delete

2024-07-25 20:19 UTC, trevorjob commented
@zxenonx i am done

2024-07-25 21:40 UTC, Goketech approved these changes

2024-07-25 21:56 UTC, zxenonx approved these changes
Thanks @trevorjob

2024-07-25 21:56 UTC, merged