[FEAT] Update Customer Details API #89
hngprojects/hng_boilerplate_python_fastapi_web pull request #427
Opened 2024-07-24 22:48 UTC by SCCSMARTCODE

## Description

This pull request introduces an API endpoint to update customer details, allowing administrators to modify customer information efficiently and securely. This update ensures that customer data remains accurate and up-to-date within the system.

## Related Issue (Link to issue ticket)
  [Issue #89: Update Customer Details API](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/89)

## Motivation and Context

This feature is crucial for maintaining accurate customer information, which is vital for effective customer management and communication. By allowing admins to update customer details, the system enhances its data integrity and overall user experience.

## How Has This Been Tested?

- **Unit Testing**: Comprehensive unit tests have been written to verify that:
  - Customer details are correctly updated when valid data is provided.
  - The system returns appropriate error responses for invalid customer IDs.
  - Unauthorized users are prevented from updating customer details.
  
- **Manual Testing**: The endpoint was manually tested using Postman to ensure proper functionality and response handling.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

---

### Acceptance Criteria

1. **Endpoint Definition:**
   - API endpoint to update customer details is implemented.

2. **Functionality:**
   - Admins can update customer details.
   - Only authorized users (admins) can perform updates.

3. **Implementation Steps:**
   - **Define API Endpoint**: The endpoint for updating customer details has been defined.
   - **Implement Logic**: Logic for updating customer information in the database has been implemented.
   - **Handle Responses**: Both success and error responses, including for invalid customer ID and unauthorized access, have been handled.
   - **Write Tests**: Tests have been written and validated to ensure functionality.

### Purpose

The endpoint aims to provide a secure and efficient way for administrators to update customer details, thereby improving the system's accuracy and data management capabilities.

### Requirements

- [x] The API follows RESTful standards.
- [x] Authorization checks are in place to restrict access to admins.
- [x] Validation for incoming data is implemented.
- [x] Appropriate success and error responses are handled.

### Expected Outcome

- Successful implementation of the endpoint.
- Secure and efficient update of customer details by admins.
- Appropriate success and error responses based on the request.
- Well-tested endpoint ensuring reliability and correctness.

### Example API Endpoint

- **Endpoint:** `PUT /api/v1/customers/:customerId`

**Request Example:**

```json
{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phone": "+1234567890",
  "address": "123 Main St, Anytown, USA"
}
```

**Successful Response Example:**

```json
{
  "status": "success",
  "status_code": 200,
  "message": "Customer details updated successfully.",
  "customer": {
    "id": "customerId",
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "phone": "+1234567890",
    "address": "123 Main St, Anytown, USA"
  }
}
```

**Error Response Examples:**

1. **Invalid Customer ID:**
   ```json
   {
     "status": "error",
     "message": "Invalid customer ID.",
     "status_code": 400
   }
   ```

2. **Unauthorized Access:**
   ```json
   {
     "status": "error",
     "message": "Unauthorized access.",
     "status_code": 401
   }
   ```

### Unit Testing

- [x] Tests for successful updates with valid data and customer ID.
- [x] Tests for error handling with invalid customer ID.
- [x] Tests for authorization checks, ensuring only admins can update customer details.

2024-07-26 09:42 UTC, joboy-dev commented on api/v1/routes/customers.py
Making db queries in routes are not allowed. Check services folder on how to use services

2024-07-26 09:43 UTC, joboy-dev commented on api/v1/services/user.py
Why are you creating adkin access token??
There's already a create access token function that works for everything

2024-07-26 09:44 UTC, joboy-dev requested changes
Make changes

2024-07-26 10:00 UTC, CodewithSegNet commented
also follow proper PR naming conventions. eg, feat: Update Customer …..

2024-07-26 10:03 UTC, CodewithSegNet reviewed
also follow proper PR naming conventions. eg, feat: Update Customer …..

2024-07-26 10:04 UTC, CodewithSegNet requested changes
also follow proper PR naming conventions. eg, feat: Update Customer …..

2024-07-26 10:56 UTC, SCCSMARTCODE commented on api/v1/routes/customers.py
This is already fixed

2024-07-26 10:58 UTC, SCCSMARTCODE commented on api/v1/services/user.py
I did this when the `get_current_user`  function only works with username but now that is works well with user_id and username 

i already remove the function

2024-07-27 11:10 UTC, joboy-dev commented on api/utils/dependencies.py
There is already a get_current_super_admin in user service

2024-07-27 11:11 UTC, joboy-dev commented on api/v1/services/customers.py
Rewrite this service file to the right format
Use a class

2024-07-27 11:12 UTC, joboy-dev requested changes
Remove .idea and resolve merge conflicts

2024-07-27 17:58 UTC, SCCSMARTCODE commented
done

On Sat, Jul 27, 2024 at 12:12 PM Adegbehingbe, Oluwakorede Joseph <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Remove .idea and resolve merge conflicts
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/427#pullrequestreview-2203160535>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BALRCJG7LOMK73O3DHXVBILZON6BTAVCNFSM6AAAAABLNMIDN2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBTGE3DANJTGU>
> .
> You are receiving this because you authored the thread.Message ID:
> <hngprojects/hng_boilerplate_python_fastapi_web/pull/427/review/2203160535
> @github.com>
>

2024-07-27 17:59 UTC, SCCSMARTCODE commented on api/utils/dependencies.py
dpne

2024-07-27 17:59 UTC, SCCSMARTCODE commented on api/v1/services/customers.py
done

2024-08-06 19:14 UTC, closed without merging