Feature/dislike blog post
hngprojects/hng_boilerplate_python_fastapi_web pull request #431
Opened 2024-07-24 22:57 UTC by traderstechie

Feature that allows users to react to a blog post with a dislike

2024-07-26 16:46 UTC, joboy-dev commented on api/v1/routes/blog.py
There's a services file for blogs. Use that to make database queries. Don't do it in routes

2024-07-26 16:47 UTC, joboy-dev requested changes
Make changes

2024-07-26 17:16 UTC, joboy-dev approved these changes

2024-07-27 10:47 UTC, joboy-dev commented on api/v1/routes/blog.py
> +        if not current_user:
No need for this

2024-07-27 10:47 UTC, joboy-dev commented on api/v1/routes/blog.py
> +    try:
No need for a try and except block

2024-07-27 10:48 UTC, joboy-dev commented on api/v1/routes/blog.py
Any database query had to be done in services

2024-07-27 10:50 UTC, joboy-dev commented on requirements.txt
> -uvloop==0.19.0
Why did you remove this

2024-07-27 10:52 UTC, joboy-dev requested changes
Make changes

2024-07-27 14:15 UTC, traderstechie commented
All requested changes made @joboy-dev

2024-07-28 12:22 UTC, closed without merging