feat: create password reset route
hngprojects/hng_boilerplate_python_fastapi_web pull request #437
Opened 2024-07-24 23:07 UTC by Myles181

## Title
Implement Password Reset Functionality via Email OTP

## Description
Implemented a password reset feature using FastAPI. This feature allows users to request a password reset by providing their email address. An OTP code is generated and sent to the user's email address, which they can use to reset their password. The endpoint does not change the password directly; it only handles OTP generation and email sending.

## Related Issue
This pull request is related to the following issue: [#IssueNumber](LinkToIssueTicket)

## Motivation and Context
This change is required to provide a secure and user-friendly way for users to reset their passwords in case they forget it. It enhances the user experience by allowing them to receive an OTP code via email, ensuring that only the rightful owner of the email address can reset the password.

## How Has This Been Tested?
- The endpoint was tested using Postman to ensure that it correctly sends an OTP to the provided email address.
- Various scenarios were tested, including:
  - Valid email address
  - Non-existent email address
  - Missing email field
- The OTP generation and email sending functionalities were tested to ensure they work as expected.
- The database was checked to ensure OTP records are created with correct expiration times.

## Screenshots (if appropriate - Postman, etc):
- **Postman Request:**
  ![Postman Request Screenshot](link_to_screenshot)
- **Postman Response:**
  ![Postman Response Screenshot](link_to_screenshot)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Additional Notes
- The `OTP` model was created to store OTP codes with fields for email, OTP code, creation time, and expiration time.
- The `password_reset` endpoint was added to handle the password reset requests.
- Custom exception handling was implemented to manage various error scenarios.

2024-07-24 23:14 UTC, joboy-dev requested changes
Why didn't you make use of services to handle DB queries??

2024-07-24 23:15 UTC, joboy-dev commented on api/v1/models/password_reset.py
> +    created_at = Column(DateTime, default=datetime.utcnow())
Remove this created_at

2024-07-24 23:15 UTC, joboy-dev requested changes
Look at suggestions

2024-07-24 23:15 UTC, joboy-dev commented on api/v1/schemas/password_reset.py
> +class EMAILSCHEMA(BaseModel):
change to EmailSchema

2024-07-24 23:53 UTC, Myles181 commented on api/v1/models/password_reset.py
> +    created_at = Column(DateTime, default=datetime.utcnow())
alright

2024-07-24 23:57 UTC, Myles181 commented on api/v1/models/password_reset.py
> +    created_at = Column(DateTime, default=datetime.utcnow())
I've removed it sir

2024-07-25 00:02 UTC, Myles181 commented on api/v1/schemas/password_reset.py
> +class EMAILSCHEMA(BaseModel):
Done sir

2024-07-25 01:52 UTC, Goketech requested changes

2024-07-25 01:52 UTC, Goketech commented on api/v1/models/newsletter.py
> +    subscribers = relationship("User", secondary=user_newsletter_association, back_populates="newsletters")
revert this change

2024-07-25 02:07 UTC, closed without merging