Feat/create password reset
hngprojects/hng_boilerplate_python_fastapi_web pull request #450
Opened 2024-07-25 02:09 UTC by Myles181

## Title
Implement Password Reset Functionality via Email OTP

## Description
Implemented a password reset feature using FastAPI. This feature allows users to request a password reset by providing their email address. An OTP code is generated and sent to the user's email address, which they can use to reset their password. The endpoint does not change the password directly; it only handles OTP generation and email sending.

## Related Issue
This pull request is related to the following issue: [#IssueNumber](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/297)

## Motivation and Context
This change is required to provide a secure and user-friendly way for users to reset their passwords in case they forget it. It enhances the user experience by allowing them to receive an OTP code via email, ensuring that only the rightful owner of the email address can reset the password.

## How Has This Been Tested?
- The endpoint was tested using Postman to ensure that it correctly sends an OTP to the provided email address.
- Various scenarios were tested, including:
  - Valid email address
  - Non-existent email address
  - Missing email field
- The OTP generation and email sending functionalities were tested to ensure they work as expected.
- The database was checked to ensure OTP records are created with correct expiration times.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Additional Notes
- The `OTP` model was created to store OTP codes with fields for email, OTP code, creation time, and expiration time.
- The `password_reset` endpoint was added to handle the password reset requests.
- Custom exception handling was implemented to manage various error scenarios.

2024-07-25 04:23 UTC, joboy-dev commented on api/v1/schemas/password_reset.py
Change from EMAILSCHEMA to EnailSchema

2024-07-25 04:24 UTC, joboy-dev requested changes
Make changes

2024-07-25 06:41 UTC, Myles181 commented on api/v1/schemas/password_reset.py
Changes are Done 👍🏾✅

2024-07-27 10:09 UTC, joboy-dev commented on api/v1/routes/password_reset.py
There are already custom exception handlers defined
Do not make db calls in routes. That is the job of services

2024-07-27 10:09 UTC, joboy-dev commented on api/v1/models/base.py
I do not know the purpose of this. There has to be a cleaner, less confusing way of handling this

2024-07-27 10:10 UTC, joboy-dev requested changes
Make changes

2024-07-27 21:28 UTC, Myles181 commented
Please I've removed that piece of code 
It was to create a relationship with the user and password_reset in another table.

2024-08-06 19:16 UTC, closed without merging