Feat/del testimonials
hngprojects/hng_boilerplate_python_fastapi_web pull request #457
Opened 2024-07-25 08:34 UTC by yvonnegichovi

## Description
This PR introduces the following changes:

- Fixed DELETE Endpoint: Improved the DELETE endpoint at `/testimonials/` to correctly delete all testimonial entries from the database.
- Pytest: Created pytest to test the newly added endpoint.

**Related Issue**
#270 

**Motivation and Context**
- The DELETE endpoint provides a way to clear all testimonials, which is useful for maintenance or testing purposes. Fixing the model warnings ensures that pytest can correctly collect and test the model without issues.

**How Has This Been Tested?**
- **Manual Testing:**
-Tested the DELETE endpoint to ensure it correctly removes all testimonials from the database.

-**Automated Testing:**

- Updated and ran unit tests using pytest to ensure all new and existing tests pass.
- Validated that the Testimonial model no longer triggers pytest warnings.

**The endpoint**
- Route `DELETE api/v1/testimonials`
- Method: DELETE
- Parameters: None

**DELETE Request Example:**

- Request URL: http://localhost:8000/testimonials/
- Response: {"message": "All testimonials deleted successfully", "data": {}, "status_code": 200}

**Types of changes**
- [x] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**
- [x]  My code follows the code style of this project.
 - [x] My change requires a change to the documentation.
- [x]  I have updated the documentation accordingly.
 - [x] I have read the CONTRIBUTING document.
 - [x] I have added tests to cover my changes.
 - [x] All new and existing tests passed.

2024-07-25 09:11 UTC, Goketech requested changes

2024-07-25 09:11 UTC, Goketech commented on .replit
> +run = ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 3000"]
remove this file

2024-07-25 09:11 UTC, Goketech commented on api/v1/models/testimonial.py
> +    author = relationship("User", back_populates="testimonials")
revert back the empty line

2024-07-25 09:11 UTC, Goketech commented on api/v1/routes/testimonial.py
> +# from api.v1.schemas.user import DeactivateUserSchema, UserBase
remove this comment

2024-07-25 09:11 UTC, Goketech commented on main.py
> -
revert this

2024-07-25 09:11 UTC, Goketech commented on requirements.txt
> -
revert this

2024-07-25 09:11 UTC, Goketech commented on api/v1/routes/testimonial.py
> +        )
do not make db queries in the routes folder, create a testimonial.py file in service and make your queries there and call the function here

2024-07-25 22:19 UTC, yvonnegichovi reviewed
Changes made as requested

2024-07-25 22:26 UTC, yvonnegichovi reviewed
Changes reviewed

2024-07-25 23:02 UTC, Goketech commented
resolve the conversations

2024-07-26 07:56 UTC, zxenonx approved these changes
Thanks @yvonnegichovi

2024-07-26 08:00 UTC, merged