Feat/request magic link
hngprojects/hng_boilerplate_python_fastapi_web pull request #477
Opened 2024-07-26 09:04 UTC by mariams58

​

## Description

This PR implements the following functionality:

**Magic Link Creation Endpoint**
+ A new endpoint `api/v1/auth/request-magic-link` is implemented to generate a unique link
+ This endpoint uses a `send_mail` service to send the unique link to the user's email address

## Related Issue (Link to issue ticket)

#476 - {FEAT] - Request Magic Link
​
### File Changes

1. **api/v1/routes/auth.py:**
+ Implemented the `request-magic-link` endpoint
+ Validate the email provided to know if user is valid
2. **api/v1/schemas/user.py:**
+ Create schema `MagicLinkRequest` to handle the request data
3. **tests/v1/test_magic_link.py:**
+ Created a test suite for the `request-magic-link` endpoint
+ Used mock services and test-specific configurations to ensure isolated and accurate testing

​## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-26 09:22 UTC, joboy-dev requested changes
Rename your PR to 
feat: request....

2024-07-26 09:40 UTC, joboy-dev commented on api/utils/send_mail.py
> +    html = f"<html><body><p>Use the following link to log in: <a href='http://localhost:8000/magic-link?token={token}'>Magic Link</a></p></body></html>"
That hostname should be dynamic
You don't want a user to see local host in their email

So update line 18 andb19

2024-07-26 09:40 UTC, joboy-dev requested changes
Make changes

2024-07-27 09:40 UTC, joboy-dev commented on tests/v1/user_deactivation_test.py
> +MAGIC_ENDPOINT = '/api/v1/auth/request-magic-link'
please remove this

2024-07-27 09:41 UTC, joboy-dev requested changes
Make changes

2024-07-29 18:39 UTC, Takinnuoye5 approved these changes
approve

2024-07-29 18:39 UTC, merged