Feat/fix: fixed conflicts and repushed Endpoint to Get specific product details by ID by Superadmin
hngprojects/hng_boilerplate_python_fastapi_web pull request #478
Opened 2024-07-26 09:35 UTC by froschi95

​

## Description

Implement a new API endpoint for retrieving product details, accessible only to superadmins. This endpoint will be part of the dashboard functionality.

#### Endpoint Details:
Path: GET /api/v1/dashboard/products/{product_id}
Access: Restricted to superadmins only

Response:
```json
{
  "status_code": 200,
  "message": "Product retrieved successfully",
  "data": {
    "id": "string",
    "name": "string",
    "description": "string",
    "price": 0.00,
    "org_id": "string"
  }
}
```

​
## Related Issue (#449 )
This PR is also related to my first PR(#466) which I had to close in order to properly resolve conflicts.

​

## Motivation and Context

​

## How Has This Been Tested?

- Unit tests were written sing pytest module to cover
 - Successful retrieval by a superadmin
 - Attempt to access by a non-superadmin user
 - Attempt to retrieve a non-existent product

​

## Screenshots (if appropriate - Postman, etc):

​

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-27 09:35 UTC, joboy-dev requested changes
Resolve conflicts

2024-07-27 21:07 UTC, froschi95 commented
> Resolve conflicts

conflicts resolved

2024-07-28 12:47 UTC, froschi95 commented
@joboy-dev

2024-07-30 19:15 UTC, joboy-dev commented on api/v1/routes/dashboard.py
> +    if product is None:
No need for this check

2024-07-30 19:15 UTC, joboy-dev commented on api/v1/routes/dashboard.py
> +    if not current_user.is_super_admin:
No need for this check

2024-07-30 19:16 UTC, joboy-dev commented on api/v1/routes/dashboard.py
> +    return DashboardProductResponse(
Use success_response() function, already in the codebase. You can check other files for how to use it

2024-07-30 19:17 UTC, joboy-dev requested changes
Pull recent changes and update your code. Thanks

2024-08-08 14:53 UTC, closed without merging