feat: dislike blog post
hngprojects/hng_boilerplate_python_fastapi_web pull request #491
Opened 2024-07-28 13:48 UTC by traderstechie

## Description:
A feature that allows users to react to a blog post with a dislike. It's a protected endpoint at `/api/v1/blogs/:{blog_id}/dislike`. It allows only authenticated users to dislike a blog post once.

## Related Issue:

[[FEAT]: Endpoint To Dislike A Blog Post #275](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/275)

## Motivation and Context
This is necessary, in order to enable blog writers to understand how readers perceive their posts.

## How Has This Been Tested?

- [x] Unittest with pytest.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:
 
- [x]  My code follows the code style of this project.
- [x]  I have updated the documentation accordingly.
- [x]  I have read the CONTRIBUTING document.
- [x]   I have added tests to cover my changes.
- [x]  All new and existing tests passed.

2024-07-28 17:39 UTC, joboy-dev requested changes
Make changes

2024-07-28 17:45 UTC, traderstechie commented on api/v1/routes/blog.py
> +        return JsonResponseDict(
Okay

2024-07-28 17:56 UTC, traderstechie commented
Changes made @joboy-dev

2024-07-29 02:32 UTC, joboy-dev commented on api/v1/routes/blog.py
Do not return success_response for errors please. Just raise HTTPException

2024-07-29 02:33 UTC, joboy-dev requested changes
Make changes

2024-07-29 13:24 UTC, Goketech approved these changes

2024-07-29 14:57 UTC, joboy-dev approved these changes

2024-07-29 14:57 UTC, merged