feat: added get user notification endpoint
hngprojects/hng_boilerplate_python_fastapi_web pull request #497
Opened 2024-07-28 16:55 UTC by trevorjob

## Description
This pull request introduces an endpoint for retrieving the current user's notifications.

The changes include
- Endpoint Addition: Added GET ``` /api/v1/notifications/me ``` for retrieving user notifications.
- Authentication: Ensured the endpoint is secured and only accessible to authenticated users.
- Validation: Implemented checks to ensure the user is authenticated before accessing notifications.
- Error Handling: Added appropriate error messages for invalid requests and authentication failures.
- Testing: Added unit and integration tests to ensure functionality and edge cases are covered.
## Related Issue (Link to issue [ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/495))

## Motivation and Context

This feature is essential to allow users to securely retrieve their notifications.

## How Has This Been Tested?

- Unit Tests: Added tests to validate the endpoint responsible for retrieving user notifications.
- Integration Tests: Included end-to-end tests to ensure proper functionality and security.
- Tests Include:
    * Retrieving notifications with a valid authentication token.
    - Handling validation errors and authentication failures.
    - Ensuring proper formatting of response data.

​

## Screenshots (if appropriate - Postman, etc):

​

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
      ​

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-07-28 17:32 UTC, joboy-dev commented on tests/v1/test_get_user_nots.py
Put this file in the notifications folder in tests/v1

2024-07-28 17:32 UTC, joboy-dev requested changes
Make changes

2024-07-28 18:29 UTC, trevorjob commented
@joboy-dev i've made the changes

2024-07-29 02:27 UTC, joboy-dev commented on api/v1/routes/notification.py
> +def get_me(
change the name to get_current_user_notifications. Something more descriptive

2024-07-29 02:27 UTC, joboy-dev commented on api/v1/routes/notification.py
> +    data = notification_service.get_me(current_user, db)
Do the same here

2024-07-29 02:28 UTC, joboy-dev commented on api/v1/services/notification.py
Nice

2024-07-29 02:28 UTC, joboy-dev requested changes
MAke changes. Sorry I didn't notice earlier

2024-07-29 07:31 UTC, trevorjob commented
@joboy-dev done

2024-07-29 18:54 UTC, Goketech approved these changes

2024-07-29 23:02 UTC, joboy-dev approved these changes

2024-07-29 23:02 UTC, merged

2024-07-29 23:48 UTC, theijhay commented
@Goketech @joboy-dev  his tests failed and you merged this?