created database schema for users, organisations, profile, product
hngprojects/hng_boilerplate_python_fastapi_web pull request #50
Opened 2024-07-18 19:28 UTC by Armolas

I added the database tables in the models file and also created an alembic folder for easy migrations.

please review the tables and merge

2024-07-18 19:37 UTC, Dev-wonderful commented
Add a proper PR comment - Description, Additions, and a checkbox of things you did that met the acceptance criteria you specified in your issue, also a link to your issue

2024-07-18 20:01 UTC, Armolas commented
I have updated the pull request comment now for your review sir

2024-07-18 21:06 UTC, zxenonx commented on api/db/database.py
> +    MYSQL_DRIVER = config("MYSQL_DRIVER", "")
we are using PostgreSql

2024-07-18 21:07 UTC, zxenonx commented on api/v1/models/base.py
> +user_organisation_association = Table('user_organisation', Base.metadata,
We'll stick to en-us across the boilerplates. 
So organization instead of organisation

2024-07-18 21:08 UTC, zxenonx commented on api/v1/models/org.py
> +class Organisation(Base):
en-us

2024-07-18 21:10 UTC, zxenonx commented on alembic/versions/9670771a11f9_initial_migrations.py
> +    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
We'll be using uuid v7 for the primary keys

2024-07-18 21:14 UTC, zxenonx commented on alembic/versions/9670771a11f9_initial_migrations.py
> +    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
Thanks @Armolas . I left some comments.

2024-07-18 22:44 UTC, bolexs commented on alembic.ini
> +sqlalchemy.url = sqlite:///./database.db
@Armolas why aren't you using postgres

2024-07-18 23:26 UTC, Armolas commented
**New Changes Added as per Request:**

> - Changed the default database to postgresql - (Please Note that testers will have to provide their local postgress database credentials through a `.env` file)
> - Changed all Organisations to Organizations for en-us support
> - Changed all model primary keys to be a uuid7 type

2024-07-19 00:10 UTC, Dev-wonderful requested changes

2024-07-19 00:36 UTC, Dev-wonderful requested changes

2024-07-19 00:36 UTC, Dev-wonderful commented on api/v1/models/profile.py
> +    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id'), nullable=False)
make it unique to establish a one-to-one

2024-07-19 06:08 UTC, Armolas commented
**New Changes As Requested by @Dev-wonderful:**

> - All `Datetime` columns are now timezone aware
> - The `profile` column of the users table now back populates to link `user` to `profile`
> - The `user_id` column on the profile table has been made `unique` to ensure proper one to one relationship

2024-07-19 06:09 UTC, Armolas commented on api/v1/models/user.py
> +    id = Column(Integer, primary_key=True, autoincrement=True)
The `id` of all the tables are already of uuid7 types boss

2024-07-19 06:12 UTC, Armolas commented on db_test.py
> +create_database()
This is just for the test file to create dummy data boss

2024-07-19 08:42 UTC, nedssoft commented
@Armolas 

Please include how this PR can be tested, from cloning to running the app to testing the endpoint; it should have enough info such that any dev can run the app and test it. You can put this information in the readme.md

2024-07-19 08:49 UTC, zxenonx commented on db_test.py
> +create_database()
we can leave it there as it's just for adding dummy data.

2024-07-19 09:51 UTC, Armolas commented
@nedssoft I have updated the README file boss

2024-07-19 09:59 UTC, Dev-wonderful approved these changes

2024-07-19 10:11 UTC, zxenonx approved these changes
Thanks @Armolas. Looks good

2024-07-19 10:13 UTC, merged