Feat/sms sending with twilio
hngprojects/hng_boilerplate_python_fastapi_web pull request #502
Opened 2024-07-28 18:22 UTC by Laban254

## Description

This pull request adds a new API endpoint `POST /api/v1/sms/send` for sending SMS messages via the Twilio API. The endpoint accepts a JSON payload containing a phone number and message content, validates the input, and sends an SMS using Twilio. It returns appropriate success or error responses based on the outcome of the SMS sending operation.

## Related Issue

[Link to the related issue ](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/42) 

## Motivation and Context

This feature allows users to send SMS messages through our application using the Twilio API. It is required for enabling communication functionality within the application.

## How Has This Been Tested?

I have tested this feature using Postman. The tests cover various scenarios, including valid and invalid inputs, and error handling. All tests have passed successfully. To run the test  
`python -m pytest tests/v1/test_sms_twilio.py`

## Screenshots (if appropriate - Postman, etc):

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ]  New feature (non-breaking change which adds functionality)
-   [ ]  Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ]  My code follows the code style of this project.
-   [ ]  My change requires a change to the documentation.
-   [ ]  I have updated the documentation accordingly.
-   [ ]  I have read the **CONTRIBUTING** document.
-   [ ]  I have added tests to cover my changes.
-   [ ]  All new and existing tests passed.

2024-07-28 19:10 UTC, joboy-dev requested changes
Tests are failing

2024-07-28 19:27 UTC, Laban254 commented
> Tests are failing
@joboy-dev  on it

2024-07-29 02:24 UTC, joboy-dev approved these changes

2024-07-29 02:24 UTC, joboy-dev commented
Fix merge conflict

2024-07-29 19:00 UTC, Goketech approved these changes

2024-07-29 22:51 UTC, closed without merging