feat: add job listing
hngprojects/hng_boilerplate_python_fastapi_web pull request #503
Opened 2024-07-28 18:48 UTC by Arnthorny

## Description
Create an API endpoint to allow users post new job listings.
This endpoint will validate the job posting and then add it to the database.
​

The changes include:
 
* **Endpoint Addition:** Added `POST /api/v1/jobs` for posting new jobs.
* **Error Handling:** Implemented checks for invalid data and unauthorized access.
* **Testing:** Added `pytest` cases to ensure functionality and edge cases are covered.
 
 
## Related Issue (Link to issue ticket)
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/490)

 ## Motivation and Context
This feature is essential to allow users post new jobs on the site.
 
 ## How Has This Been Tested?
 * **Unit Tests:** Added tests to validate the addition of jobs to the database, authorization failures and invalid request body.
* **Test Environment:** Tests were run using a mocked database instance to avoid interference with the production environment.

Tests include:
 
* Adding a job to the database successfully.
* Handling invalid request body
* Handling unauthorized access.

## Screenshots:
### Successful Request
![image](https://github.com/user-attachments/assets/ef208a99-38bb-4197-ba61-ec13ad096037)

### Invalid request body
![image](https://github.com/user-attachments/assets/fd14e10c-cea0-44c9-9224-95734449e62c)

## Types of changes
* [x]  New feature (non-breaking change which adds functionality)
 
 ## Checklist:
 * [x]  My code follows the code style of this project.
 * [x]  My change requires a change to the documentation.
 * [x]  I have updated the documentation accordingly.
 * [x]  I have read the **CONTRIBUTING** document.
 * [x]  I have added tests to cover my changes.
 * [x]  All new and existing tests passed.

2024-07-28 19:12 UTC, joboy-dev commented on api/v1/routes/jobs.py
> +    except Exception as e:
Exceptions are already being handled by the app. No need for this

2024-07-28 19:13 UTC, joboy-dev requested changes
Make changes and I will merge

2024-07-28 21:50 UTC, Arnthorny commented
> Make changes and I will merge

@joboy-dev Changes implemented

2024-07-29 02:16 UTC, joboy-dev commented
Merge conflict!!

2024-07-29 04:53 UTC, Arnthorny commented
> Merge conflict!!

Merge conflict resolved @joboy-dev

2024-07-29 05:44 UTC, Arnthorny commented
> Merge conflict!!

Conflict resolved.

Following the new conventions, this endpoint should only be accessible by an admin.
@joboy-dev

2024-07-29 17:50 UTC, Goketech approved these changes

2024-07-29 17:50 UTC, merged