Feat/job update
hngprojects/hng_boilerplate_python_fastapi_web pull request #515
Opened 2024-07-29 01:07 UTC by Myles181

# Update Job Route Implementation

## Description

This pull request introduces the implementation of the job update route in our application. The update route allows users to modify existing job entries with new data. The update functionality is essential for maintaining accurate and up-to-date job postings.

## Related Issue (Link to issue ticket)

## Motivation and Context

This change is required to enable users to update existing job entries, ensuring that the job postings reflect the latest information. It solves the problem of outdated job postings, providing a way for users to manage and edit job details as necessary.

## How Has This Been Tested?

- **Unit Tests**: Added unit tests to verify the update route functionality, ensuring that jobs are correctly updated with valid data and appropriate error messages are returned for invalid requests.
- **Integration Tests**: Conducted integration tests using Postman to confirm that the update route interacts correctly with the database and handles various edge cases.
- **Manual Testing**: Performed manual testing in a development environment to ensure that the user interface for updating job postings works as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-29 02:04 UTC, joboy-dev commented on api/v1/routes/job_update.py
I have said it over and over again not to make db queries in routes. There should be separation of concern
Check services folder on how to use services

2024-07-29 02:05 UTC, joboy-dev requested changes
Rename your PR to feat: job update
Link this PR to an open issue. If there is none, create one
Write tests as well

2024-07-29 15:18 UTC, Myles181 commented on api/v1/routes/job_update.py
I just updated it Sir

2024-07-30 19:12 UTC, joboy-dev commented on api/v1/services/job.py
Alright, do something for me
Check other service files like the faq service to see how update was implemented in the service and update your code accordingly
Thanks

2024-07-30 19:13 UTC, joboy-dev commented on api/v1/routes/job_update.py
Check faq routes file for how to handle update requests. Thanks

2024-07-30 19:13 UTC, joboy-dev requested changes
Make changes and I will merge. This is not bad

2024-08-05 23:06 UTC, closed without merging