feat: superadmin delete organisation by id
hngprojects/hng_boilerplate_python_fastapi_web pull request #559
Opened 2024-07-30 03:18 UTC by chionz

## Description

This pull request introduces a new endpoint that allows superadmin users to delete an organization by its ID. The implementation ensures that only authorized superadmin accounts can perform this action.

Key Changes:
- Created a DELETE endpoint at `/api/v1/superadmin/organizations/{org_id}`.
- Implemented authorization checks to ensure only superadmin users can access this endpoint.
- Added logic to handle cases where the specified organization does not exist, returning a 404 Not Found status.
- Implemented error handling to return a 500 Internal Server Error in case of unexpected issues.

## Related Issue (Link to issue ticket)

issues 371 https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/371

## Motivation and Context

This change is required to provide superadmin users with the capability to delete organizations within the application. It enhances security by restricting this functionality to authorized users and ensures proper error handling and response statuses, aligning with the defined acceptance criteria.

## How Has This Been Tested?

The implementation has been tested as follows:
- **Successful Deletion**: Verified that an organization is successfully deleted when a valid ID is provided by a superadmin.
- **Organization Not Found**: Ensured that a 404 Not Found response is returned when attempting to delete a non-existent organization.
- **Unauthorized Access**: Confirmed that non-superadmin users are unable to access the delete endpoint.
- **Server Error Handling**: Simulated server errors to verify that a 500 Internal Server Error response is appropriately returned.

Tests were conducted using [appropriate testing tools/environments] to validate the functionality and ensure no regression in the codebase.

## Screenshots (if appropriate - Postman, etc):

![Screenshot from 2024-07-30 04-09-35](https://github.com/user-attachments/assets/69ea15a5-b622-4efe-9b08-4a1b8d71b21f)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-31 14:02 UTC, joboy-dev commented on api/v1/routes/organization.py
> +    organization = db.query(Organization).filter(Organization.id == org_id).first()
Don't make db queries in the routes. Do it with services.

2024-07-31 14:03 UTC, joboy-dev commented on api/v1/services/organization.py
Can you update this function
There's a lot of typos so instead of product, it should be organization 

Thanks

2024-07-31 14:03 UTC, joboy-dev approved these changes

2024-07-31 14:03 UTC, joboy-dev requested changes
Make changes

2024-07-31 18:25 UTC, chionz commented
@joboy-dev I have made changes.
please check

2024-07-31 19:23 UTC, joboy-dev approved these changes

2024-08-01 07:29 UTC, joboy-dev approved these changes

2024-08-01 13:55 UTC, Goketech approved these changes

2024-08-01 13:55 UTC, merged