feat: get organization users
hngprojects/hng_boilerplate_python_fastapi_web pull request #571
Opened 2024-07-30 10:02 UTC by chukssomzzy

## Description
This feature allows getting all users in an organization. It facilitates the retrieving of users in an organization by pagination of the users for effective retrieval

## Related Issue
[FEAT: Fetch all Users of an Organisation API - BACKEND](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/78)

## Motivation and Context
This change is necessary to provide functionality for getting all organization users, enhancing the flexibility and usability of the application. It solves the problem of not being able to get all organization users.

## How Has This Been Tested?
- [X] Tested extensively with Postman.
- [X] Written working unittests with pytest.

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/b490fd11-f657-49ed-9e10-10f8da32f12f)

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-30 17:49 UTC, joboy-dev commented on api/v1/routes/organization.py
Do this
Pull latest changes and use the paginated_response function in api/utils/pagination.py to generate a paginated response
Thanks

2024-07-30 17:50 UTC, joboy-dev requested changes
Make changes

2024-07-30 18:36 UTC, chukssomzzy commented on api/v1/routes/organization.py
It not possible to use paginated_response function, since it doesn't do a join.

2024-07-30 20:05 UTC, chukssomzzy commented
> Make changes

requested changes has been made. 
I am using paginate_response to paginate response and I have merged current changes

2024-07-31 01:02 UTC, joboy-dev commented on api/v1/routes/organization.py
Oh. So you were doing a join?
Okat

2024-07-31 01:03 UTC, joboy-dev approved these changes

2024-07-31 12:58 UTC, joboy-dev approved these changes

2024-07-31 14:05 UTC, joboy-dev approved these changes

2024-07-31 14:36 UTC, CodewithSegNet approved these changes

2024-07-31 15:03 UTC, joboy-dev approved these changes

2024-07-31 15:04 UTC, merged