Feature/newsletter unsubscription
hngprojects/hng_boilerplate_python_fastapi_web pull request #653
Opened 2024-08-01 15:55 UTC by CaptainAril

# Pull Request: Endpoint for deleting blog post

## Description
This pull request implements a new API endpoint for unsubscribing from the newsletter. The endpoint will accept an email address, validate and sanitize it, and then handle both successful and failed validations appropriately. If the email passes validation and exists in the database, it will be removed, and a 'success' response will be sent to the client. If the email does not exist, an error message will be returned

## Changes
- Added a new POST endpoint `/api/v1/pages/newsletter/unsubscribe`
- Added delete functionality for newsletter subscription
- Added comprehensive test coverage for the new endpoint

## Code Changes

### File: `/api/v1/pages/newsletter/unsubscribe`

```python
@newsletter.post('/pages/newsletter/unsubscribe')
async def unsubscribe(request: EmailSchema, db: Session = Depends(get_db)):
    NewsletterService.delete(db=db,  request=request)
    
    return success_response(
        status_code=200,
        message="You have unsubscribed from our newsletter."
    )

```

## Related Issue
Closes #652

2024-08-01 21:03 UTC, joboy-dev commented
Update this PR
The name and the content is confusing
Which are you doing, blog or newsletter??

2024-08-01 21:15 UTC, joboy-dev approved these changes

2024-08-06 01:39 UTC, joboy-dev commented on tests/v1/newsletter/newsletter_test.py
What happened here

2024-08-06 01:39 UTC, joboy-dev requested changes
What happened to that test file you just removed

2024-08-06 01:40 UTC, Goketech requested changes

2024-08-06 01:40 UTC, Goketech commented on tests/v1/newsletter/newsletter_test.py
> -        mocker.patch.object(NewsletterService, 'fetch_all', return_value=mock_subs)
you removed the tests in this file, revert changes

2024-08-22 22:16 UTC, closed without merging